### ISSUE TITLE
Unrecognized arguments base_dir and use_gpt2_tokenizer

### ISSUE THREAD

**Issue by RecursiveDescent** [EleutherAI/gpt-neo#112]
`create_tfrecords.py: error: unrecognized arguments: --base_dir /content/GPTNeo/openwebtext --use_gpt2_tokenizer`

I even tried using input_dir instead of base_dir and without gpt2_tokenizer. I think that worked, but when I got to copying data to the storage bucket it did this instead: `No URLs matched: /content/GPTNeo/openwebtext_tokenized`
I tried to make folders in the bucket to match the path but nothing worked.

**Comment by srulikbd** [comment]
yeah it maked me also some problems, but worked at last. but I couldn't train..there is some bug over there.

**Comment by gdimopoulos** [comment]
Same here. Modified the command like this:
`!python data/create_tfrecords.py --mode documents --input_dir /content/GPTNeo/$dataset_path --name $dataset_name --output_dir $out_name --write_dataset_config`

The command fails with this error:
`Traceback (most recent call last):
  File "data/create_tfrecords.py", line 205, in <module>
    results = create_tfrecords_mp(files, args)
  File "data/create_tfrecords.py", line 186, in create_tfrecords_mp
    files = split_list(files, len(files) // args.processes)
  File "data/create_tfrecords.py", line 67, in split_list
    return [l[i:i+n] for i in range(0, len(l), n)]
ValueError: range() arg 3 must not be zero
`

**Comment by 322997am** [comment]
> Same here. Modified the command like this:
> `!python data/create_tfrecords.py --mode documents --input_dir /content/GPTNeo/$dataset_path --name $dataset_name --output_dir $out_name --write_dataset_config`
> 
> The command fails with this error:
> `Traceback (most recent call last): File "data/create_tfrecords.py", line 205, in <module> results = create_tfrecords_mp(files, args) File "data/create_tfrecords.py", line 186, in create_tfrecords_mp files = split_list(files, len(files) // args.processes) File "data/create_tfrecords.py", line 67, in split_list return [l[i:i+n] for i in range(0, len(l), n)] ValueError: range() arg 3 must not be zero `

This happens when the number of documents in the dataset is smaller than the amount of CPUs you have. Set the argument `--processes 1` to address this

**Comment by StellaAthena** [comment]
> `create_tfrecords.py: error: unrecognized arguments: --base_dir /content/GPTNeo/openwebtext --use_gpt2_tokenizer`
> 
> I even tried using input_dir instead of base_dir and without gpt2_tokenizer. I think that worked, but when I got to copying data to the storage bucket it did this instead: `No URLs matched: /content/GPTNeo/openwebtext_tokenized`
> I tried to make folders in the bucket to match the path but nothing worked.

The project documentation is a little out of date. using `input_dir` and dropping `use_gpt2_tokenizer` is the correct way to use the code. Can you elaborate on what goes wrong when you make those changes?

**Comment by StellaAthena** [comment]
> Same here. Modified the command like this:
> `!python data/create_tfrecords.py --mode documents --input_dir /content/GPTNeo/$dataset_path --name $dataset_name --output_dir $out_name --write_dataset_config`
> 
> The command fails with this error:
> `Traceback (most recent call last): File "data/create_tfrecords.py", line 205, in <module> results = create_tfrecords_mp(files, args) File "data/create_tfrecords.py", line 186, in create_tfrecords_mp files = split_list(files, len(files) // args.processes) File "data/create_tfrecords.py", line 67, in split_list return [l[i:i+n] for i in range(0, len(l), n)] ValueError: range() arg 3 must not be zero `

As explained by @322997am this is an unrelated error and is caused by the fact that you have more CPUs trying to create TFRecords than you have documents. You should either increase the number of documents or only use some of your CPUs to create TFRecords. The flag `--processes n` allows you to limit the number of parallel processes being employed.

**Comment by StellaAthena** [comment]
Hi! Thanks for the feedback. We pushed some updates including a totally revamped notebook, give it a try and let me know if you're still getting this error.
