### ISSUE TITLE
Colab breaks when tokenizing NIH Dataset

### ISSUE THREAD

**Issue by Muennighoff** [EleutherAI/gpt-neo#134]
Traceback (most recent call last):
  File "data/create_tfrecords.py", line 205, in <module>
    results = create_tfrecords_mp(files, args)
  File "data/create_tfrecords.py", line 186, in create_tfrecords_mp
    files = split_list(files, len(files) // args.processes)
  File "data/create_tfrecords.py", line 67, in split_list
    return [l[i:i+n] for i in range(0, len(l), n)]
ValueError: range() arg 3 must not be zero

I'll look into why it breaks

**Comment by StellaAthena** [comment]
What is the value of `n` when this line executes? Where was it set

**Comment by Muennighoff** [comment]
> What is the value of `n` when this line executes? Where was it set

yeah i found the problem it seems because of two cpu's on colab in create_tfrecords_mp(files, args):

len(files) // args.processes = 1 // 2 = 0

what about instead we use:

- ( - len(files) // args.processes) = 1 ; for 1 file and args.processes >=1

**Comment by StellaAthena** [comment]
What advantage does this have over `max(1, len(files) // arg.processes)`? I haven't stress tested the code you wrote, but that seems more intuitive to me.

I'm also surprised you had this problem in the first place.  `files` is the number of files in your input directory, which is apparently 1. If you only have 1 file why are you trying to use multiple CPUs?

**Comment by Muennighoff** [comment]
> What advantage does this have over `max(1, len(files) // arg.processes)`? I haven't stress tested the code you wrote, but that seems more intuitive to me. It's definitely more transparent.
> 
> I'm also surprised you had this problem in the first place. `files` is the number of files in your input directory, which is apparently 1. If you only have 1 file why are you trying to use multiple CPUs?

The code is the same just that it rounds up instead of down
I wasn't explicitly trying to use multiple cpus, it's just that by default colab apparently gives you access to two cpus hence multiprocessing.cpu_count = 2. I think you should still be able to process 1 file even if you have two active cpus
