### ISSUE TITLE
Transformative Mediation

### ISSUE THREAD

**Issue by fuzzyTew** [EleutherAI/gpt-neo#139]
Is anybody discussing training models wisely?  It seems it would even be best to train models based on crowd sourced human feedback on something like what leaves everyone understood and respected.  Is this reasonable to do?

Here is tiny booklet on nonviolent communication, a mediation process that has reliably ended long-running wars and family squabbles with a little bit of talk: https://gateway.ipfs.io/ipfs/QmdFVjYwgeuUpw83hBB74Wy4js8SrmmNxt8U2MkdRA2f7m/Books/We%20Can%20Work%20It%20Out:%20Resolving%20Conflicts%20Peacefully%20and%20Powerfully.pdf .  There are many long books on NVC, too.

**Comment by StellaAthena** [comment]
If you have a dataset I will happily look at it. However I think you massively overestimate the level of kindness found in crowdsourced text.

**Comment by xloem** [comment]
@StellaAthena thank you so much for your reply.  The ipfs folder I linked to has a handful of books in it in its parent folder.  Would sets of pdfs like that work as a dataset?  Do you know how many would be needed?

Regarding the kindness of crowdsourced text, that seems pretty solvable.  For example, you could use a decaying transitive trust among peers, and select root users with human review; even automate the trust using string similarity.  Any thoughts?

**Comment by StellaAthena** [comment]
> @StellaAthena thank you so much for your reply. The ipfs folder I linked to has a handful of books in it in its parent folder. Would sets of pdfs like that work as a dataset? Do you know how many would be needed?

A model like GPT-3 is trained on approximately 800 GB of pure text. 1GB of ASCII text is 900,000 pages. To comprise 1% of the training data, you would need to provide 7.2 million pages of text. To have a significant impact on steering the trained model, I would recommend aiming for 100 million pages of text.

> Regarding the kindness of crowdsourced text, that seems pretty solvable. For example, you could use a decaying transitive trust among peers, and select root users with human review; even automate the trust using string similarity. Any thoughts?
> 
> (edit: further thoughts of mine: I suspect it would be most political if the people in the crowdsourced text could consent on who the examples of "good communication" were.)

I don't know if you have any experience implementing such a system, but it's a lot easier to say "oh just do this" than it is to actually do it. What you're asking for is a massive technical and social effort that would take months of full-time work. Then many years would be required to collect the necessary submissions of text. If you were to somehow obtain 1 million users each submitting a page of validated content per day, it would take several years to amasss the necessary data.

**Comment by xloem** [comment]
> A model like GPT-3 is trained on approximately 800 GB of pure text. 1GB of ASCII text is 900,000 pages. To comprise 1% of the training data, you would need to provide 7.2 million pages of text. To have a significant impact on steering the trained model, I would recommend aiming for 100 million pages of text.

Thanks.  That's a lot of text.

I'm really thinking there's a way to do this with less text.  For example, training a poor quality model, offering the model as a chatbot, then using its filtered or weighted history as a new dataset.  With the right weights, it could be trended towards respectful, understanding dialogue (or anything else).  Is there any way to make a low quality model using only a little text?

> > Regarding the kindness of crowdsourced text, that seems pretty solvable. For example, you could use a decaying transitive trust among peers, and select root users with human review; even automate the trust using string similarity. Any thoughts?
> > (edit: further thoughts of mine: I suspect it would be most political if the people in the crowdsourced text could consent on who the examples of "good communication" were.)
> 
> I don't know if you have any experience implementing such a system, but it's a lot easier to say "oh just do this" than it is to actually do it. What you're asking for is a massive technical and social effort that would take months of full-time work. Then many years would be required to collect the necessary submissions of text. If you were to somehow obtain 1 million users each submitting a page of validated content per day, it would take several years to amasss the necessary data.

Months of work to graph text by similarity to some valued phrases, and filter them based on distance?

But yeah, I'm thinking of what kinds of supporting software projects would help make the future bright with language models.  Making hard things is possible.  I'm not asking you to make these things, yourself.

**Comment by xloem** [comment]
I found the Discord.  Thanks for your patience with me in this issue.

I hope somewhere people are holding respectful mediation as a goal.  If that means making millions of examples of mediating, then we'd better start the work.
