### ISSUE TITLE
Link to dataset is not available

### ISSUE THREAD

**Issue by zilunpeng** [EleutherAI/gpt-neo#140]
The link (https://eaidata.bmk.sh/data/hn.tar.gz) to HackerNews dataset in GPTNeo_example_notebook.ipynb is not available. Could you provide a new link?

**Comment by StellaAthena** [comment]
Unfortunately that dataset is no longer available, as we deleted it to free up some space. I recommend using [OpenWebText2](https://openwebtext2.readthedocs.io/en/latest/) instead. OpenWebText2 is an extension of the OpenWebText dataset that we created. It uses a similar methodology but is much larger and has better filtering.
