### ISSUE TITLE
Does this support distributed training?

### ISSUE THREAD

**Issue by CrazyPython** [EleutherAI/gpt-neo#141]
Does this support distributed training? For instance, when multiple people want to pool computation power to contribute it.

**Comment by StellaAthena** [comment]
This code is designed to run on TPUs. You are very likely better off pooling you’re resources to rent time on larger TPUs than each renting and sharing.

if you’re interested in training on GPUs, check out www.GitHub.com/eleutherai/gpt-neox which has our GPU code and does support distributed training.
