### ISSUE TITLE
Colab notebook create_tfrecords.py: unknown argument "--mode documents"

### ISSUE THREAD

**Issue by mlaugharn** [EleutherAI/gpt-neo#146]
**Describe the bug**
The argument parser seems to no longer support the "--mode documents" from the Colab notebook

**To Reproduce**
1. Follow the Colab notebook

**Proposed solution**
Remove the argument in the Colab tutorial notebook

**Environment (please complete the following information):**
Google Colab

**Comment by sdtblck** [comment]
Oops, sorry for this. That's deprecated, and the argument can be removed. I'll update the notebook now.

**Comment by sdtblck** [comment]
Ok, fixed! Thanks for bringing it to my attention

https://github.com/EleutherAI/gpt-neo/commit/61a1ea413eac88d81a7bc295cc356a16a4dd4208
