### ISSUE TITLE
Provide more options for inference

### ISSUE THREAD

**Issue by JanPokorny** [EleutherAI/gpt-neo#157]
I would like to see some more options for the inference, especially a way to control the heat. Additionally, it would be nice to have an option to write the inferred text to a file (the stdout output is currently mixed with all the logging stuff).

**Comment by asasr** [comment]
fhad1012@icloud.com

**Comment by sdtblck** [comment]
Hey @JanPokorny , thanks for the issue. 

The sampling is already saved to a text file (`predictions_[step_number]_nosacred.txt`).

In terms of options for sampling, those are accessible via this function https://github.com/EleutherAI/gpt-neo/blob/3d91883a238649f8fdb5f42e6ae9e33002bd276d/sample.py#L8 / https://github.com/EleutherAI/gpt-neo/blob/master/model_fns.py#L99

I will try to integrate some command line options for that when I have time, but we're open to PRs, too :)
