### ISSUE TITLE
Way to manipulate a length of generated text (maximum length)

### ISSUE THREAD

**Issue by ArturTan** [EleutherAI/gpt-neo#162]
Hi,

I tried to generate shorter text (less than 2048 tokens) via `--predict`, manipulating "n_ctx". However, without success. If there is such a possibility, please let me know, because the documentation, nor notebook doesn't provide any information on that. 

Best

**Comment by StellaAthena** [comment]
Thanks for your interest! The notebook is a just quick demo that people can use to get started – you can fully manipulate the model using the codebase.

That said, this is an auto regressive model. To generate 15 characters, you can just run the model until it generates 15 characters and then exit.
