### ISSUE TITLE
Making predictions deterministic

### ISSUE THREAD

**Issue by zilunpeng** [EleutherAI/gpt-neo#164]
Thanks for the great work!!

I was trying to set a seed and make predictions (sampling) deterministic. Here is what I have tried: 

In `main.py`, add `tf.set_random_seed(32)`

In `main.py`, modify:

```
config = tpu_config.RunConfig(
        tf_random_seed = 32,
        cluster=tpu_cluster_resolver,
        model_dir=params["model_path"],
        save_checkpoints_steps=None,  # Disable the default saver
        save_checkpoints_secs=None,  # Disable the default saver
        log_step_count_steps=params["iterations"],
        save_summary_steps=params["iterations"],
        tpu_config=tpu_config.TPUConfig(
            num_shards=mesh_shape.size,
            iterations_per_loop=params["iterations"],
            num_cores_per_replica=1,
            per_host_input_for_training=tpu_config.InputPipelineConfig.BROADCAST))
```

With the above setup, results are still inconsistent between runs. Any ideas on where randomness may come from?

**Comment by StellaAthena** [comment]
It depends a bit on how you’re running the code, but [this](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) might be helpful. In particular, if rerunning the function returns different results but restarting the TPU and running from scratch produces the same sequence of results, you need to set the “operational seed” in addition to the “global seed.”

It’s also very possible that there are additional sources of randomness in mesh tensorflow that `tf.random` doesn’t interact with.

If your interest is primarily in doing inference it will likely be easier to use the HuggingFace (WIP) code [here](https://github.com/huggingface/transformers/pull/10848).
