### ISSUE TITLE
Any way to run model without payment method on gcloud?

### ISSUE THREAD

**Issue by qpwo** [EleutherAI/gpt-neo#172]
**Is your feature request related to a problem? Please describe.**

If you try to just straight run the colab notebook then you get an error on bucket creation. Need billing to create bucket.

**Describe the solution you'd like**

I think if data is stored in public read-only bucket then you could run the model without risking billing yourself on accident.

**Describe alternatives you've considered**

If you could avoid the bucket altogether and somehow run on the notebook machine's local filesystem that would be good too.

**Additional context**

This is the notebook from the readme I am referring to: https://colab.research.google.com/github/EleutherAI/GPTNeo/blob/master/GPTNeo_example_notebook.ipynb

**Comment by StellaAthena** [comment]
You do not need to pay money to use this model. A free Google Cloud account gives you much more storage space than you need. If you’ve used up your free credits, you could try to create another account I guess?

You cannot load local files onto a TPU. That’s a Google restriction. You can run the model entirely locally, but you can’t load a local model onto TPU.
