### ISSUE TITLE
The README is a lie

### ISSUE THREAD

**Issue by shawwn** [EleutherAI/gpt-neo#188]
The README reads:

> An implementation of model & data parallel GPT2 & GPT3 -like models, with the ability to scale up to full GPT3 sizes (and possibly more!)

This is not true. It doesn't matter if you've done a few training steps at 200B. It would take over a decade to train on a v3-256, even under the most generous assumptions possible.

Even if full GPT-3 were released tomorrow, it would inference at a rate of around 4 words per minute, minimum. And I'd bet money the real rate is much slower.

It's a bit like advertising a cure for cancer, then leaving out that it only works if the patient dies first. Wouldn't you feel a little mislead?

Theranos did the same thing with their blood tests: told investors it'd work, when in fact under normal conditions it could never work.

I don't understand why everyone is fine with being deceptive. Replicating 1.5B was legitimately cool. There was no need to front.

**Comment by sdtblck** [comment]
Thanks Shawwn, we updated the readme to make this clear. https://github.com/EleutherAI/gpt-neo/commit/e88120c457dac0a4b05067b0fa25ba197ea9e5de#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by shawwn** [comment]
![image](https://user-images.githubusercontent.com/59632/113458371-e6ce0080-93c6-11eb-9ce6-b2a578be2884.png)

The repository description still says it. Should I open a different issue?
