### ISSUE TITLE
How do we decrease inference speed? 

### ISSUE THREAD

**Issue by EnterHub** [EleutherAI/gpt-neo#189]
Hi

Great job on this. It's really impressive and I've enjoyed playing around with it in a Google Colab TPU-environment

I though about a toy project, where i would make a web interface, so everybody can play around with it, without setting up an environment etc. For that to be reality, i think we need to decrease the inference speed. In a Google Colab TPU-enviroment it takes it about 5 minutes to infer a result.

Has anybody looked into how to decrease that to a few seconds? 

Thanks!

**Comment by EnterHub** [comment]
Found a solution, so I'm closing this one.

**Comment by royherma** [comment]
Hey @EnterHub, would love to know what you did! Mind sharing? 🙌

**Comment by StellaAthena** [comment]
> Hey @EnterHub, would love to know what you did! Mind sharing? 🙌

The main problem is that Mesh TF reloads the computational graph each time you call inference. It should be able to keep the NN in memory the whole time, but MTF is written in a way that makes that difficult for no apparently reason. I don’t know what solution the OP has, but I expect that this is what they found a work-around for.

**Comment by PandaWhoCodes** [comment]
> Mesh TF reloads the computational graph each time you call inference. It should be able to keep the NN in memory the whole time, but MTF is written in a way that makes that difficult for no apparently reason. I don’t know what solution the OP has

would love it if you could share the solution here as well
