### ISSUE TITLE
Stop Sequences

### ISSUE THREAD

**Issue by jaehyunshinML** [EleutherAI/gpt-neo#195]
First of all, Thanks for the great effort and kind instruction. 

In the GPT3 playground, there are a Stop Sequences which limit the number of generation of text.  
It would be great if we can add something to stop the generation so we can generate only a sentence to speed up the whole process.

**Comment by StellaAthena** [comment]
This is not a feature we plan on adding, though we are certainly open to pull requests.

In general, I recommend you use the [HuggingFace](https://github.com/huggingface/transformers) interface provides much better and more user-friendly interaction than we could. It has this feature already implemented.
