### ISSUE TITLE
How to get text embedding vector by gpt-neo-1.3B model?

### ISSUE THREAD

**Issue by Bennu-Li** [EleutherAI/gpt-neo#197]
I want to compare the similarity between the two sentences by calculating the similarity of two sentence vectors. Therefore， I want to know how can I get the sentence vector by the pre-traind model gpt-neo-1.3B?

**Comment by StellaAthena** [comment]
I recommend you use the [HuggingFace](https://github.com/huggingface/transformers) interface
```
from transformers import AutoTokenizer, AutoModelForCausalLM
  
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")
model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B")
```
for working with the model. See the HuggingFace documentation for futher info.
