### ISSUE TITLE
Intermediate checkpoints?

### ISSUE THREAD

**Issue by matthiasgalle** [EleutherAI/gpt-neo#198]
Cool work, thanks for doing this!
Do you, or are you planning to, release **intermediate checkpoints** of these models? The apparently emergent characteristics of these models is impressive, and it would be interesting to see if there are specific moments when those start appearing.

**Comment by StellaAthena** [comment]
We did not save intermediate checkpoints for these models, though we may make an effort to do so in the future if people are interested. What level of gradation would you be interested in?

**Comment by matthiasgalle** [comment]
we are at least two: https://twitter.com/lintool/status/1371933868677300252 :D 

as for the granularity, of course the more the merrier, but I guess that having 10 (evenly spaced?) between the initial and the final released one would already allow to observe some evolution.
