### ISSUE TITLE
dummy tfrecord file could not be downloaded.

### ISSUE THREAD

**Issue by zshyang** [EleutherAI/gpt-neo#199]
When I run the following command line,
```
 wget https://storage.googleapis.com/connors-datasets/bundestag/bundestag_0.tfrecords
```
I have got the following error. Could you help me? Thanks!
```
--2021-04-08 17:05:10--  https://storage.googleapis.com/connors-datasets/bundestag/bundestag_0.tfrecords
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.73.208, 142.250.73.240, 172.217.2.112, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.73.208|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-08 17:05:10 ERROR 403: Forbidden.
```

**Comment by StellaAthena** [comment]
This indicates that your settings on Google Cloud are not set up correctly. It may be that you haven’t validated your credentials properly, or that your GCloud settings prevent this type of query.

**Comment by zshyang** [comment]
Do you know how to fix it? Thank you very much. And I am not using Google Cloud. I am using my local GPU. I think that would be the case for some of people.

**Comment by StellaAthena** [comment]
Well that must be at least some of the problem. It's trying to access Google Cloud.
