### ISSUE TITLE
Documentation request: How to convert a GPTNeo TF checkpoint into a huggingface supported model

### ISSUE THREAD

**Issue by Norod** [EleutherAI/gpt-neo#210]
Hello,
I was wondering if GPTNeo checkpoints can also be converted using the [transformers-cli convert](https://huggingface.co/transformers/converting_tensorflow_models.html) command. If this is indeed the case, what should be passed as --model_type? Will passing "gpt2" work?

**Comment by StellaAthena** [comment]
I do not know, this is a question better asked of HuggingFace. I would guess that you should pass "gpt_neo" as the model type if you want to make a gpt_neo model.

**Comment by Norod** [comment]
In case someone finds it useful, I found the script which converts gpt_neo checkpoints into HuggingFace  pytorch and generates a matching config json. It's available here: https://github.com/huggingface/transformers/blob/master/src/transformers/models/gpt_neo/convert_gpt_neo_mesh_tf_to_pytorch.py
