### ISSUE TITLE
GPT Neo Colab: no such file or directory "data/create_tfrecords.py"

### ISSUE THREAD

**Issue by audiodude** [EleutherAI/gpt-neo#212]
**Describe the bug**
In GPTNeo_example_notebook.ipynb, getting an error in cell 8: python3: can't open file 'data/create_tfrecords.py': [Errno 2] No such file or directory

**To Reproduce**
1. Go to https://colab.research.google.com/github/EleutherAI/GPTNeo/blob/master/GPTNeo_example_notebook.ipynb
2. Link with Google Cloud
3. Select "Custom" data set and enter relative path and filename from cloud bucket

**Expected behavior**
When running cell 8, the data referenced above is tokenized and later available

**Proposed solution**
It doesn't look like there is a data/ directory included with the notebook

**Screenshots**
<img width="1188" alt="Screen Shot 2021-04-28 at 7 16 28 PM" src="https://user-images.githubusercontent.com/57832/116494714-44365f80-a856-11eb-978e-51acf41e33d6.png">

**Environment (please complete the following information):**
Google Colab

**Additional context**

**Comment by StellaAthena** [comment]
The required function does in fact exist, as you can see [here](https://github.com/EleutherAI/gpt-neo/blob/master/data/create_tfrecords.py). I don't know why it's unable to be found... is your working directory set to the main `gpt-neo` directory?

**Comment by audiodude** [comment]
I'm using the colab linked from the README

**Comment by StellaAthena** [comment]
Yes, I'm asking you to check where your working directory is set on collab.

**Comment by audiodude** [comment]
Oh sorry.

<img width="291" alt="Screen Shot 2021-04-29 at 7 07 22 PM" src="https://user-images.githubusercontent.com/57832/116639819-3d731f80-a91e-11eb-9398-f1abb61bc84e.png">

**Comment by StellaAthena** [comment]
Well that’s your problem. There is not in fact a `data/create_tfrecords.py` on your Colab instance. You probably installed it wrong or changed the WD without realizing it. If you can’t figure out how to restore the files, you should just make a new Colab instance and redo it.

**Comment by audiodude** [comment]
I tried looking for the gpt-neo directory on the notebook, but I couldn't find it anywhere. Do you know where it's supposed to be located?

As far as I know, I didn't run any commands to change the working directory myself, I only ran commands from the notebook, so maybe I just did them in the wrong order and that caused the problem?

**Comment by audiodude** [comment]
Okay I solved it by uploading a zip of the repo to the colab, then unzipping it in the content/ directory. Thanks!
