### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by fire17** [EleutherAI/gpt-neo#214]
Hey there!
Was wondering if anyone has made an API for this ?

I would like to send REST with a text query and get a human-like response. Hopefully featuring the latest model

Also while I'm here, could this be used multilingual ?

Thanks a lot !

**Comment by StellaAthena** [comment]
Thank you for your interest!

We have no plans on making a REST API. There are some places that offer query access to pretrained GPT-Neo, including HuggingFace, but we do not.

The model was overwhelmingly trained on English text (> 95%).  We do not recommend using on other languages without first training it further.

**Comment by fire17** [comment]
I've tried the one over huggingface, it's pretty cool bot it completes my sentences, not answer them . 
Could this be achieved with a certain model ?
Does anyone know if a good chatbot api ?
Thx a lot!
