### ISSUE TITLE
OSError: Can't load weights for 'EleutherAI/gpt-neo-125M'

### ISSUE THREAD

**Issue by MK096** [EleutherAI/gpt-neo#219]
While running the model on my PC on python shell i always get the error :

_OSError: Can't load weights for 'EleutherAI/gpt-neo-125M'. Make sure that:

- 'EleutherAI/gpt-neo-125M' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'EleutherAI/gpt-neo-125M' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt._

Initially it usually downloads upto 20% then the downloading speed reduces to 1kbps and then after a while i get this error.

Code:
from happytransformer import HappyGeneration
from transformers import pipeline

happy_gen = HappyGeneration(model_type="GPT-NEO", model_name="EleutherAI/gpt-neo-125M") 
result = happy_gen.generate_text("To solve world hunger we must invest in ")
 print(result)

**Error :** 

Downloading:  20%|##        | 108M/526M [06:40<121:13:26, 959B/s]  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\modeling_utils.py", line 1141, in from_pretrained
    user_agent=user_agent,
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\file_utils.py", line 1279, in cached_path
    local_files_only=local_files_only,
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\file_utils.py", line 1534, in get_from_cache
    http_get(url_to_download, temp_file, proxies=proxies, resume_size=resume_size, headers=headers)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\file_utils.py", line 1393, in http_get
    for chunk in r.iter_content(chunk_size=1024):
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\pipelines\base.py", line 95, in infer_framework_from_model
    model = model_class.from_pretrained(model, **model_kwargs)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\models\auto\auto_factory.py", line 381, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\modeling_utils.py", line 1150, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load weights for 'EleutherAI/gpt-neo-125M'. Make sure that:

- 'EleutherAI/gpt-neo-125M' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'EleutherAI/gpt-neo-125M' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mayank\Documents\Python_Save\GPT-NEO\neo-1.py", line 17, in <module>
    funB()
  File "C:\Users\Mayank\Documents\Python_Save\GPT-NEO\neo-1.py", line 13, in funB
    generator = pipeline('text-generation', model='EleutherAI/gpt-neo-125M')
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\pipelines\__init__.py", line 389, in pipeline
    framework, model = infer_framework_from_model(model, targeted_task, revision=revision, task=task)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\pipelines\base.py", line 98, in infer_framework_from_model
    model = model_class.from_pretrained(model, **model_kwargs)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\models\auto\auto_factory.py", line 383, in from_pretrained
    f"Unrecognized configuration class {config.__class__} for this kind of AutoModel: {cls.__name__}.\n"
ValueError: Unrecognized configuration class <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoConfig'> for this kind of AutoModel: TFAutoModelForCausalLM.
Model type should be one of BertConfig, OpenAIGPTConfig, GPT2Config, TransfoXLConfig, XLNetConfig, XLMConfig, CTRLConfig.
>>>

**Comment by haroon19** [comment]
> 
> 
> While running the model on my PC on python shell i always get the error :
> 
> _OSError: Can't load weights for 'EleutherAI/gpt-neo-125M'. Make sure that:
> 
>     * 'EleutherAI/gpt-neo-125M' is a correct model identifier listed on 'https://huggingface.co/models'
> 
>     * or 'EleutherAI/gpt-neo-125M' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt._
> 
> 
> Initially it usually downloads upto 20% then the downloading speed reduces to 1kbps and then after a while i get this error.
> 
> Code:
> from happytransformer import HappyGeneration
> from transformers import pipeline
> 
> happy_gen = HappyGeneration(model_type="GPT-NEO", model_name="EleutherAI/gpt-neo-125M")
> result = happy_gen.generate_text("To solve world hunger we must invest in ")
> print(result)
> 
> **Error :**
> 
> Downloading: 20%|## | 108M/526M [06:40<121:13:26, 959B/s] File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 494, in stream
> data = self.read(amt=amt, decode_content=decode_content)
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 459, in read
> raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in **exit**
> self.gen.throw(type, value, traceback)
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 378, in _error_catcher
> raise ProtocolError('Connection broken: %r' % e, e)
> urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\modeling_utils.py", line 1141, in from_pretrained
> user_agent=user_agent,
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\file_utils.py", line 1279, in cached_path
> local_files_only=local_files_only,
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\file_utils.py", line 1534, in get_from_cache
> http_get(url_to_download, temp_file, proxies=proxies, resume_size=resume_size, headers=headers)
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\file_utils.py", line 1393, in http_get
> for chunk in r.iter_content(chunk_size=1024):
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 753, in generate
> raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\pipelines\base.py", line 95, in infer_framework_from_model
> model = model_class.from_pretrained(model, **model_kwargs)
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\models\auto\auto_factory.py", line 381, in from_pretrained
> return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\modeling_utils.py", line 1150, in from_pretrained
> raise EnvironmentError(msg)
> OSError: Can't load weights for 'EleutherAI/gpt-neo-125M'. Make sure that:
> 
>     * 'EleutherAI/gpt-neo-125M' is a correct model identifier listed on 'https://huggingface.co/models'
> 
>     * or 'EleutherAI/gpt-neo-125M' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\Mayank\Documents\Python_Save\GPT-NEO\neo-1.py", line 17, in
> funB()
> File "C:\Users\Mayank\Documents\Python_Save\GPT-NEO\neo-1.py", line 13, in funB
> generator = pipeline('text-generation', model='EleutherAI/gpt-neo-125M')
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\pipelines__init__.py", line 389, in pipeline
> framework, model = infer_framework_from_model(model, targeted_task, revision=revision, task=task)
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\pipelines\base.py", line 98, in infer_framework_from_model
> model = model_class.from_pretrained(model, **model_kwargs)
> File "C:\Users\Mayank\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\models\auto\auto_factory.py", line 383, in from_pretrained
> f"Unrecognized configuration class {config.**class**} for this kind of AutoModel: {cls.**name**}.\n"
> ValueError: Unrecognized configuration class <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoConfig'> for this kind of AutoModel: TFAutoModelForCausalLM.
> Model type should be one of BertConfig, OpenAIGPTConfig, GPT2Config, TransfoXLConfig, XLNetConfig, XLMConfig, CTRLConfig.
> 
> > > >

I am experiencing the same error, progress stops at 54% and terminates, tried with both 1.3B and 2.7B models. Is there any way that we download these pretrained models on our local machine and instead of downloading them from live we serve them from our local machine ?

**Comment by StellaAthena** [comment]
The README has a direct link to where you can download them from the-eye.eu

**Comment by MK096** [comment]
@StellaAthena Thanks,  i will try that out

**Comment by ixn872** [comment]
@StellaAthena  I believe the eye only uploaded the billion parameter models
