### ISSUE TITLE
Can't sample from GPT3 2.7B model

### ISSUE THREAD

**Issue by texturejc** [EleutherAI/gpt-neo#224]
I wish to sample from the GPT3 2.7B pretrained model. I appreciate that Huggingface offer a pipeline for this, but it isn't working (I've filed the issue with them), and I'd like the greater control from my own notebook in any event. I've already successfully run the smaller GPT Neo models. 

When I run to the supplied colab, notebook, it all works fine until I try to sample from the pretrained model. When I do, I get an assertion error:

```
Traceback (most recent call last):
  File "main.py", line 257, in <module>
    main(args)
  File "main.py", line 56, in main
    params = fetch_model_params(args.model)
  File "/content/GPTNeo/configs.py", line 29, in fetch_model_params
    assert dataset_id in DATASETS, f"Dataset '{dataset_id}' was not found under dataset_configs/ folder. Please follow the example.json in that folder."
```

I've spent a fair amount of time trying to get to the bottom of this by manually pasting URLs into the code etc, but nothing seems to work. So far as I can tell, it's acting as if I want to fine tune the model on a dataset rather than just sample from it. Can anyone advise on what may be happening here? Thanks

**Comment by texturejc** [comment]
Don't know if anyone is looking at this, but for reference the colab instructions work fine with the GPT3_XL model; this problem seems specific to the GPT 2.7B version.

**Comment by StellaAthena** [comment]
There is a limitation in the way our code is organized that requires you to have a dataset on-hand if you want to sample. The dataset is not used, but you need a valid dataset that you could train on.
