### ISSUE TITLE
Can't load GPT3_XL

### ISSUE THREAD

**Issue by MK096** [EleutherAI/gpt-neo#226]
Hi All,
I downloaded the model from 
 https://the-eye.eu/public/AI/gptneo-release/GPT3_XL/

after which i changed model_path in config.json to:
"model_path" : "C:\\Users\\GPT_NEO_2\\GPT3_XL" 

Whenever i run the following code: 
 _model = GPTNeoForCausalLM.from_pretrained("C:\\Users\\GPT_NEO_2\\GPT3_XL")_

i get an error:
f"Error no file named {[WEIGHTS_NAME, TF2_WEIGHTS_NAME, TF_WEIGHTS_NAME + '.index', FLAX_WEIGHTS_NAME]} found in "
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index', 'flax_model.msgpack'] found in directory C:\\Users\\GPT_NEO_2\\GPT3_XL or `from_tf` and `from_flax` set to False.

and while running :
_generator = pipeline('text-generation', model="C:\\Users\\GPT_NEO_2\\GPT3_XL")_

i get following error:
f"Unrecognized model in {pretrained_model_name_or_path}. "

I have the latest TF and torch (both cpu).

Thanks

I have aloso attached my config.json
![config](https://user-images.githubusercontent.com/20142735/121779893-4e6aae00-cbb7-11eb-82fc-4eb3f1adbf83.PNG)

**Comment by StellaAthena** [comment]
Please double check that you have downloaded all the files from the eye. There is a `.index` file on the eye.

**Comment by MK096** [comment]
> Please double check that you have downloaded all the files from the eye. There is a `.index` file on the eye.

Yes, that is there along with config. Json and several checkpoints.. 
Also, how do I make use of the checkpoints?

**Comment by MK096** [comment]
> Please double check that you have downloaded all the files from the eye. There is a `.index` file on the eye.

There is no .index files. I have attached the files that i got
![gpt_files](https://user-images.githubusercontent.com/20142735/121919924-f23b9180-cd50-11eb-91bc-1f86a479d25e.PNG)

Also, how do I make use of the checkpoints?

**Comment by StellaAthena** [comment]
> > Please double check that you have downloaded all the files from the eye. There is a `.index` file on the eye.
> 
> There is no .index files. I have attached the files that i got

In that case it seems like you failed to download everything. If you visit [this link](https://the-eye.eu/public/AI/gptneo-release/GPT3_XL/) you'll see that there is a `.index` file there.

**Comment by MK096** [comment]
> > > Please double check that you have downloaded all the files from the eye. There is a `.index` file on the eye.
> > 
> > 
> > There is no .index files. I have attached the files that i got
> 
> In that case it seems like you failed to download everything. If you visit [this link](https://the-eye.eu/public/AI/gptneo-release/GPT3_XL/) you'll see that there is a `.index` file there.

I re downloaded everything. 
While running the model i get following error now:
https://github.com/EleutherAI/gpt-neo/issues/227#issuecomment-860830169

**Comment by StellaAthena** [comment]
Great! You are now officially out of our hands... this is a GPU configuration issue on your end. I recommend checking out multiGPU training documentation for whatever framework you are using. [This issue](https://github.com/google-research/text-to-text-transfer-transformer/issues/334) may also be helpful.
