### ISSUE TITLE
The_Eye hosted models wont download

### ISSUE THREAD

**Issue by diskreet90** [EleutherAI/gpt-neo#231]
Hey there, I'm using the colab to possibly finetune GPT3 XL, but when I get to the step about using wget in download the weights, it gives me a 406 error. I can go to the website and download each file separately but that would take ages to download only to add to a bucket. Any thoughts or ideas, and possibly what I could be doing wrong?

**Comment by shawwn** [comment]
Weems to work fine for me, both on my local laptop and in colab:

```
wget -m -np -c -U eye02 -w 2 -R index.html\* https://the-eye.eu/public/AI/gptneo-release/GPT3_XL/
```

![image](https://user-images.githubusercontent.com/59632/123989306-63ed1f80-d98e-11eb-9284-78b058768bd5.png)

Are you running this notebook, or a different one? https://colab.research.google.com/github/EleutherAI/GPTNeo/blob/master/GPTNeo_example_notebook.ipynb#scrollTo=GU3BDNJN_ZXE

**Comment by AlexanderKozhevin** [comment]
@shawwn do you know where to download GPT-J 6B weight?
It's shown in hugging face
<img width="936" alt="Screenshot 2021-08-29 at 13 38 53" src="https://user-images.githubusercontent.com/4464561/131247449-bead8695-063b-4b1a-b350-7a637a54e77a.png">

**Comment by StellaAthena** [comment]
> @shawwn do you know where to download GPT-J 6B weight?
> It's shown in hugging face
> <img alt="Screenshot 2021-08-29 at 13 38 53" width="936" src="https://user-images.githubusercontent.com/4464561/131247449-bead8695-063b-4b1a-b350-7a637a54e77a.png">

Main repo: https://github.com/kingoflolz/mesh-transformer-jax
HuggingFace: https://huggingface.co/EleutherAI/gpt-j-6B
