### ISSUE TITLE
Tokenizing error when training on Colab

### ISSUE THREAD

**Issue by Marcus-Arcadius** [EleutherAI/gpt-neo#233]
![image](https://user-images.githubusercontent.com/78793842/124851748-77c7ff80-dfe6-11eb-9733-0d5ab252cfc7.png)

**Comment by bterrific2008** [comment]
You seem to have a double slash in your path, and you seem to be referencing your `gdrive` from the colab directory.

Are you mounting your Google Drive correctly with your colab notebook? Here's a [stackoverflow](https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/master/colab-notebooks/GDrive-Resize.ipynb) answer about the subject.

**Comment by Marcus-Arcadius** [comment]
> You seem to have a double slash in your path, and you seem to be referencing your `gdrive` from the colab directory.
> 
> Are you mounting your Google Drive correctly with your colab notebook? Here's a [stackoverflow](https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/master/colab-notebooks/GDrive-Resize.ipynb) answer about the subject.

Sorry for the late reply, I honestly thought no one would answer, yes I am mounting my drive to the notebook!

**Comment by Marcus-Arcadius** [comment]
@bterrific2008 I was unable to get it to work by any means, I believe it may be a problem with the notebook code

**Comment by Marcus-Arcadius** [comment]
@bterrific2008  I managed to get it to finally work, but now I am experiencing these problems?
![image](https://user-images.githubusercontent.com/78793842/126885658-775d6e78-2d50-4628-b7ca-61d4dffcafa1.png)

**Comment by bterrific2008** [comment]
The error states `FileNotFoundError` for the `configs/colab_XL.json` file. Can you check if your working directory is in the gpt-neo repository, and if there exists a `configs/colab_XL.json` file in your copy of the gpt-neo repo?

**Comment by Marcus-Arcadius** [comment]
> The error states `FileNotFoundError` for the `configs/colab_XL.json` file. Can you check if your working directory is in the gpt-neo repository, and if there exists a `configs/colab_XL.json` file in your copy of the gpt-neo repo?

I cannot find any file in my copy 
![image](https://user-images.githubusercontent.com/78793842/126886075-4eb65246-5c35-40c4-be7e-ec8d5d59d6dd.png)

**Comment by StellaAthena** [comment]
> > The error states `FileNotFoundError` for the `configs/colab_XL.json` file. Can you check if your working directory is in the gpt-neo repository, and if there exists a `configs/colab_XL.json` file in your copy of the gpt-neo repo?
> 
> I cannot find any file in my copy
> ![image](https://user-images.githubusercontent.com/78793842/126886075-4eb65246-5c35-40c4-be7e-ec8d5d59d6dd.png)

Try loading `configs/gpt3_XL_256_Pile.json` instead.

**Comment by bterrific2008** [comment]
From my understanding of the notebook, whatever file you write to in the `Set Model Configs` is the configuration file you should use for the `Training from Scratch` step.

The help text for the `--model` parameter of `main.py` reads as: `JSON file that contains model parameters`, so you should make sure whatever is contained there matches the config file you want to use.

**Comment by Marcus-Arcadius** [comment]
> From my understanding of the notebook, whatever file you write to in the `Set Model Configs` is the configuration file you should use for the `Training from Scratch` step.
> 
> The help text for the `--model` parameter of `main.py` reads as: `JSON file that contains model parameters`, so you should make sure whatever is contained there matches the config file you want to use.

As I could not get it to work, I ended up using the pre-trained model for fine tuning - it worked. If in the future, I want to further train the fine-tuned model, what is the process?
