### ISSUE TITLE
Is It Possible To Continue Finetuning From Checkpoints on Any GPT-Neo Model?

### ISSUE THREAD

**Issue by IndianBoy6** [EleutherAI/gpt-neo#234]
I want to finetune a huge dataset on Google Colab so I won't be able to run it in  1 session. After the session disconnects, I have the weights saved in Google Cloud. Is there any way I can keep finetuning from those weights?

**Comment by StellaAthena** [comment]
Yes, just load them as a checkpoint and run the training script.
