### ISSUE TITLE
Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [EleutherAI/gpt-neo#239]
Hello,I found a performance issue in the definition of `lambada_input` ,
EleutherAI/gpt-neo/blob/master/tasks.py,
[dataset.map](https://github.com/EleutherAI/gpt-neo/blob/5f3055b026652b1a2e64bb8330cdcc054ef8bf6e/tasks.py#L104) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by StellaAthena** [comment]
Please do open a PR, ideally with plots showing the performance gain

**Comment by DLPerf** [comment]
Ok,I am willing to offer you a PR.But do you have some benchmark tools?It'd be more convient if you provide me your benchmark tools.
