### ISSUE TITLE
Performance issue in tasks.py

### ISSUE THREAD

**Issue by DLPerf** [EleutherAI/gpt-neo#240]
**Describe the bug**
I've found a performance issue in "tasks.py": `dataset = dataset.batch(params['eval_batch_size'], drop_remainder=True)`[(here)](https://github.com/EleutherAI/gpt-neo/blob/5f3055b026652b1a2e64bb8330cdcc054ef8bf6e/tasks.py#L105) should be called before `dataset = dataset.map(_get_output)`[(here)](https://github.com/EleutherAI/gpt-neo/blob/5f3055b026652b1a2e64bb8330cdcc054ef8bf6e/tasks.py#L104), which would make your program more efficient.
Here is [the tensorflow document](https://tensorflow.google.cn/guide/data_performance?hl=zh_cn#vectorized_mapping) to support this thing.

**To Reproduce**
1. Go to "tasks.py"
2. Scroll down to line 104
3. See error

**Expected behavior**
call `dataset = dataset.batch(params['eval_batch_size'], drop_remainder=True)` before `dataset = dataset.map(_get_output)`

**Proposed solution**
Swap the order of `dataset = dataset.map(_get_output)` and `dataset = dataset.batch(params['eval_batch_size'], drop_remainder=True)` in "tasks.py".
Besides, you need to check the function `_get_output`[(here)](https://github.com/EleutherAI/gpt-neo/blob/5f3055b026652b1a2e64bb8330cdcc054ef8bf6e/tasks.py#L92) called in `dataset.map()` whether to be affected or not to make the changed code work properly. For example, if `_get_output` needs data with shape(x, y, z) as its input before fix, it will require data with shape(batch_size, x, y, z).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by StellaAthena** [comment]
Thanks for letting us know! It would be awesome if you could submit a PR with plots showing the performance improvement

**Comment by DLPerf** [comment]
Thanks for your reply! Is there any benchmark to show the performance of function `lambada_input`[(here)](https://github.com/EleutherAI/gpt-neo/blob/5f3055b026652b1a2e64bb8330cdcc054ef8bf6e/tasks.py#L84)? @StellaAthena

**Comment by StellaAthena** [comment]
> Thanks for your reply! Is there any benchmark to show the performance of function `lambada_input`[(here)](https://github.com/EleutherAI/gpt-neo/blob/5f3055b026652b1a2e64bb8330cdcc054ef8bf6e/tasks.py#L84)? @StellaAthena

Maybe I’m misunderstanding, but I was expecting you to run the code both ways and use a timer to show how long it takes.

**Comment by DLPerf** [comment]
OK, 
I'll try my best to run the code and calculate the time it takes.
Thank you, dear Stella. @StellaAthena
