### ISSUE TITLE
Where to download model for EleutherAI/gpt-j-6B

### ISSUE THREAD

**Issue by AlexanderKozhevin** [EleutherAI/gpt-neo#245]
I checked out colab https://colab.research.google.com/github/EleutherAI/GPTNeo/blob/master/GPTNeo_example_notebook.ipynb#scrollTo=lgTG1ammqGB0

But there is only GPT3_XL and GPT3_2-7B.
Where can I find 6B?

**Comment by StellaAthena** [comment]
Main repo: https://github.com/kingoflolz/mesh-transformer-jax
HuggingFace: https://huggingface.co/EleutherAI/gpt-j-6B
