### ISSUE TITLE
Error when connecting to Google Cloud Storage

### ISSUE THREAD

**Issue by goaaats** [EleutherAI/gpt-neo#247]
**Describe the bug**
In the Colab training workbook, after running the setup step, connecting to Google Cloud and entering the access code, the "Set up Google Cloud" step fails with the following error:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-6c5f6545616c> in <module>()
      1 from google.colab import auth
----> 2 auth.authenticate_user()
      3 get_ipython().system('gcloud init')

2 frames
/usr/local/lib/python3.7/dist-packages/tensorflow_gcs_config/__init__.py in _load_library(filename, lib)
     55   raise NotImplementedError(
     56       "unable to open file: " +
---> 57       "{}, from paths: {}\ncaused by: {}".format(filename, filenames, errs))
     58 
     59 _gcs_config_so = _load_library("_gcs_config_ops.so")

NotImplementedError: unable to open file: _gcs_config_ops.so, from paths: ['/usr/local/lib/python3.7/dist-packages/tensorflow_gcs_config/_gcs_config_ops.so']
caused by: ['/usr/local/lib/python3.7/dist-packages/tensorflow_gcs_config/_gcs_config_ops.so: undefined symbol: _ZN10tensorflow15OpKernelContext5inputEN4absl12lts_2021032411string_viewEPPKNS_6TensorE']
```

**To Reproduce**
1. Open the training colab workbook
2. Run the setup step
3. Run the "Set up Google Cloud" step
4. Enter your access code
5. See the error

**Expected behavior**
The Google Cloud setup should not fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/16760685/132955078-560b7d6e-7a59-422b-9a44-8e3d654c314c.png)

**Environment (please complete the following information):**
Google Colab with TPU

**Comment by StellaAthena** [comment]
This works for me, so I suspect the issue is with your Google Cloud settings.
