### ISSUE TITLE
Issues with Argument defaulting in `data/create_tfrecords.py`

### ISSUE THREAD

**Issue by reshinthadithyan** [EleutherAI/gpt-neo#249]
**Describe the bug**
The default argument for wikitext and ftfy has been set `True`. Whereas by default people tend to think that unspecified arguments to default to `False`.  

**To Reproduce**
1. Go to https://github.com/EleutherAI/gpt-neo/blob/7fbd31be724aefd5e59b4eca2e5dd3416b7b97eb/data/create_tfrecords.py#L28  and https://github.com/EleutherAI/gpt-neo/blob/7fbd31be724aefd5e59b4eca2e5dd3416b7b97eb/data/create_tfrecords.py#L29
**Expected behavior**
The unused arguments should default to `False`.
**Proposed solution**
The arguments like wikitext and ftfy should hold `store_true`.

**Comment by StellaAthena** [comment]
You are correct that there is the potential for confusion here, but this is the intended behavior not a bug.
