### ISSUE TITLE
How to fine tine gptneo for QA dataset?

### ISSUE THREAD

**Issue by shankyemcee** [EleutherAI/gpt-neo#250]
I would like to fine tune this model to my custom QA dataset where the input is a question and a data table, and the output is an answer to the question. How can I have this setup for this model? I can keep the answers in the tf_records as target output of model but where would input questions and data table go?

**Comment by StellaAthena** [comment]
I'm not sure I understand the question... the input questions and data table go as the model input.

**Comment by dshkliarenko** [comment]
Could you please clarify the way (if any) to pass input_text (**feature**) and target_text (**label**) for training? Right now I can't see that it's implemented.

**Comment by StellaAthena** [comment]
This  code base only supports autoregressive training. This means that you need to reprocess your data into something along the lines of
`|Task Name|Train|Val|Test|Val/Test Docs|Metrics|\n|-----|-----|-----|-----|-----|-----|\n| cola |✓|✓||1043|mcc|\n|mnli|✓|✓||9815|acc|\n|mnli_mismatched|✓|✓||9832|acc|`
and then treat it like normal text (note that this is the first three lines of [this table](https://github.com/EleutherAI/lm-evaluation-harness#full-task-list). Alternatively you can use a pretrained GPT-Neo model as a text feature extraction model, and run the table through some other model before concatenating the embeddings.
