### ISSUE TITLE
Predict runtime error  

### ISSUE THREAD

**Issue by Borshig** [EleutherAI/gpt-neo#251]
**Describe the bug**
Predict runtime error 

**To Reproduce**

i run:
   python main.py --model "GPTModels\GPT3_XL\config.json" --auto_layout_and_mesh_shape --gpu_ids device:gpu:0 --predict --prompt example_prompt.txt

and get error (as in the screeenshot)
looks like mesh-tensorflow dont know or dont correctly detect my single gpu device.

**Screenshots**
![image](https://user-images.githubusercontent.com/17796364/138526631-ac76fce8-d88f-4534-8336-5676d839da7e.png)

**Environment (please complete the following information):**
- GPUs: 3080ti
- Configs: GPT3_XL

**Additional context**

i tried different spellings "gpu:0", "0", same

i dont know what's wrong.

**Comment by sarangzambare** [comment]
Same error here, was anyone able to fix this ? 

GPU: 2080 Ti
Python 3.8.6

**Comment by StellaAthena** [comment]
We do not officially support GPU with this codebase. People have had success using it with GPUs, but some meaningful changes are necessary.

**Comment by sarangzambare** [comment]
Understood. If you happen to know any repositories/forks that have had success with GPUs, do let us know.
