### ISSUE TITLE
Generation should allow user to specify max length of generated portion, rather than total

### ISSUE THREAD

**Issue by monsieurpooh** [EleutherAI/gpt-neo#268]
The max_length arg requires us to specify a max length of the input and output combined. Also, it represents the number of tokens rather than chars. This isn't useful because we can't precisely calculate the number of tokens in the input; we can only get an estimate. So there is no way to specify to the model whether we want it to generate 1 extra token or 200 extra tokens. I don't understand why there isn't already a way to specify the number of tokens to generate rather than total tokens, or why it would ever be more useful to specify total number rather than generated number. 

Is there any workaround to this? I looked into GPT2Tokenizer but still am not sure how to get the # of tokens in the input.

**Comment by monsieurpooh** [comment]
Bump, in case anyone knows the answer (I suspect there is an easy way to get the number of tokens in the prompt and then calculate the desired tokens to generate as a workaround, and I'm just not understanding it)

**Comment by monsieurpooh** [comment]
I am a little confused because the documentation seems to imply the length of input_ids will be the number of tokens https://github.com/huggingface/transformers/blob/master/src/transformers/models/gpt2/tokenization_gpt2.py#L115

But when running the code input_ids is always a length of 1

**Comment by monsieurpooh** [comment]
For the workaround: It's a 1-element list whose only element is the real list, so Just do input_ids[0] to get token length, and add this to the specified max tokens.

**Comment by monsieurpooh** [comment]
I only just discovered the max_new_tokens arg in the documentation which seems to be expressly for this purpose. Weird that no one's mentioned it yet

**Comment by StellaAthena** [comment]
I'm sorry that you're frustrated by the fact we weren't able to get to this issue, but I'm glad you found what you were looking for by reading the documentation.
