### ISSUE TITLE
ERROR: transformers 3.5.1 has requirement tokenizers==0.9.3

### ISSUE THREAD

**Issue by stanistolberg** [EleutherAI/gpt-neo#78]
Hi,
in colab on the requirements.txt one get following error
`ERROR: transformers 3.5.1 has requirement tokenizers==0.9.3, but you'll have tokenizers 0.8.1rc2 which is incompatible.`

**Comment by StrangeTcy** [comment]
It's the same for me, except the transformers version is different: `ERROR: transformers 4.1.1 has requirement tokenizers==0.9.4, but you'll have tokenizers 0.8.1rc2 which is incompatible.`

**Comment by MulinT-UN** [comment]
Same issue here with an additional error

> ERROR: ortools 8.1.8487 has requirement absl-py>=0.11, but you'll have absl-py 0.10.0 which is incompatible.

> ERROR: transformers 4.3.0 has requirement tokenizers<0.11,>=0.10.1, but you'll have tokenizers 0.9.4 which is incompatible.

**Comment by StellaAthena** [comment]
If you remove the version restrictions and just use the most recent version of both `transformers` and `tokenizers` does anything go wrong?

**Comment by Wikidepia** [comment]
> If you remove the version restrictions and just use the most recent version of both `transformers` and `tokenizers` does anything go wrong?

It works fine here tested by using create_tfrecords
